### ISSUE TITLE
Block MMI?

### ISSUE THREAD

**Issue by spacedingo** [apsun/NekoSMS#15]
Can we also get to block Cell broadcast/MMI messages? Maybe a separate module? I really like your filtering and other options like notification.

There's a working MMI blocker here, but it doesn't have GUI or filter. https://github.com/agentdr8/NoMMI

**Comment by apsun** [comment]
Erm, sorry, I have no idea what MMI is...  mind uploading a screenshot? ;-p

**Comment by spacedingo** [comment]
USSD/MMI a part of GSM, but not in newer LTE. Basically one can dial a *123# or *130# or *123*111222333# to check their prepaid balance or remaining data, or scratchable prepaid cards to top up credit. Then you'd get a message on your screen. A lot of time there's spam too.
![screenshot_20160325-231525](https://cloud.githubusercontent.com/assets/471376/14052243/1d993278-f2e2-11e5-8935-d00bd0395083.png)
Another screenshot
https://stackoverflow.com/questions/20286608/is-it-possible-to-read-the-call-cost-history-from-dialogue-raised-after-ending-t

**Comment by apsun** [comment]
So the idea is that you call a certain number, and get a message back in the form of a dialog? I don't think it would be worth the effort, since you already have to go through the process of dialing the number anyways. Also, I don't know of a way I could actually test this; my carrier doesn't offer this feature, sorry :-(

I suppose you could make a request on XDA developers or something, though.
