### ISSUE TITLE
打开某些文件时偶尔会跳转到导入备份的界面。

### ISSUE THREAD

**Issue by jiacai-wang** [apsun/NekoSMS#31]
安卓5.1，用自带的下载器下载某些安装包之后，点击打开的时候会被识别为备份文件。在文件浏览器找到安装包然后打开安装就不会跳到导入备份。
有些安装包会被识别为备份文件，有些又不会，找不到规律。

：）

**Comment by apsun** [comment]
Might be due to the APK file's MIME type being set to `application/octet-stream`. [NekoSMS handles this](https://github.com/apsun/NekoSMS/blob/master/AndroidManifest.xml#L56) so you can open backup files directly from email. I'll try to think of a way around this, but for now, try clearing the defaults for NekoSMS.

**Comment by apsun** [comment]
Unfortunately it seems the way Android (and Gmail) handles file types is stupid and there's no way to check the file extension from Gmail. So there's 2 options, both of which are bad:

1. Don't allow backup files to be opened from Gmail directly.

2. Have issues where random files are incorrectly opened with NekoSMS.

**Comment by 1576186685** [comment]
I know little about Android and programming......
Anyway, thanks for your module.

**Comment by apsun** [comment]
就是说有些情况下，Android无法区分NekoSMS的备份文件和其他格式的文件。要么选false positive（现在就是这么做的），要么选false negative（一些情况下无法打开NekoSMS备份）

**Comment by 1576186685** [comment]
就是说不能通过文件后缀和大小判断，直接是由系统决定的，先天不足无法治愈咯？

**Comment by apsun** [comment]
一般是可以的，但是有些地方（比如说email附件和你说的下载管理器）无法读取文件名
