### ISSUE TITLE
Question regarding NekoSMS sender contains condition

### ISSUE THREAD

**Issue by Burnzero** [apsun/NekoSMS#42]
Hi,

 -   Device: OnePlus 5
 -  Android version: 7.1.1
 -  Xposed version: 88.2
 -  NekoSMS version: 0.15.0

There is some senders with name AT650011 and AT650003 from my carrier. Its all just promotional spam messages.

I created a rule to block this. The rule is:

if sender contains AT6500 - case insensitive.

This should block, but it isn't blocking.

In Xposed log, I just get:

```
12-05 12:21:26.711 I/Xposed  ( 7202): NekoSMS: Allowed message (matched whitelist or no matching rules)
```

But if I have the same condition to body, then it works. What could be the issue?

Thanks.

**Comment by apsun** [comment]
What is the full sender address? You can find it in the Messaging app by long pressing on a message and clicking the (i) icon for full details. Not sure about other SMS apps, but they should have a similar feature.

**Comment by Burnzero** [comment]
Do you mean the number? If so, it is 28650011. I got this by pressing the phone button on that message ( that will call that sender of that message). But sender name is AT650011.

I don't see any options to get the full sender address by long pressing the message.

**Comment by apsun** [comment]
Try writing your rule using 28650011 instead of AT650011. The number you see in your SMS app might not be the actual number in the SMS data.

If you want to know the number for sure, you can write a filter that just blocks everything. The number that gets displayed in the blocked messages list is the raw sender number (what you want to match on).

On that note, I think it would probably be a good idea to have a switch in the settings that enables verbose filter logging to help debug situations like this.

**Comment by Burnzero** [comment]
Thank you. I now blocked all the messages in the NEKO SMS to check the original number. I will update you here when I get that information.

Thanks again for creating this mod. :)

**Comment by Burnzero** [comment]
Awesome @apsun . As per your advice, I blocked all messages and when I check in Neko SMS app, I see the blocked messages from AT650011 ( which was displayed as sender in my messaging app ) is now being displayed as AT-650011 in Neko SMS app. So it is clear that the default messaging app in Oneplus 5 is modifying the sender display name.

So I now created the filter with '-' character.

Thank you for your support.
