### ISSUE TITLE
Use storage access framework to write files

### ISSUE THREAD

**Issue by sharp-tasting** [apsun/NekoSMS#50]
This isn't a bug report, just a feature suggestion. 

Using the storage access framework you will be able to support all kinds of removable storage supported by Android (e.g. secondary external storage like an SD card). Additionally users can save files to supported cloud storage providers without you having to add special support for them ourselves.
This will also allow you to drop the permission to write to external storage.

https://developer.android.com/guide/topics/providers/document-provider

---

**If you are submitting a bug report and do not include the following info, your issue will be ignored!**

- Device: mido (redmi note 4 with LineageOS 15.1 unofficial)
- Android version: 8.1.0
- Xposed version: 90.2-beta3
- NekoSMS version: 0.16.0

Please paste your Xposed logs (Xposed Installer -> Logs -> Menu -> Save to SD card) below:

```
Replace this line with your logs. Do not remove the backticks.
```

Thank you for helping us help you help us all.

**Comment by apsun** [comment]
Are you referring to `ACTION_CREATE_DOCUMENT` and `ACTION_OPEN_DOCUMENT`? I can't remember why I decided to roll my own solution, I think it was because the built-in UI for those intents was horrible back in the Lollipop days and didn't support third party file managers; not sure if it's gotten better in the past few years. Maybe if I have time I'll give it another shot, thanks for your suggestion.

**Comment by apsun** [comment]
Done in c12a8720543485061e3e32c4ff259832d21026dd (mostly because Android Q is going to force me to do it)
