### ISSUE TITLE
希望增加一个规则共享的功能

### ISSUE THREAD

**Issue by dudu485** [apsun/NekoSMS#59]
建议
1、增加一个公有规则共享的功能，可以上传下载
2、apple store上有款软件workflow 是把复杂的流程图形化的，参照他们的做法，把正则规则可视化，让更多哪怕不懂正则规则的人都可以编写属于自己的拦截规则

---

**If you are submitting a bug report and do not include the following info, your issue will be ignored!**

- Device: 
- Android version: 
- Xposed version: 
- NekoSMS version: 

Please paste your Xposed logs (Xposed Installer -> Logs -> Menu -> Save to SD card) below:

```
Replace this line with your logs. Do not remove the backticks.
```

Thank you for helping us help you help us all.

**Comment by apsun** [comment]
1. You can already export to the SD card, then use a file browser app to sync it to/from the internet. I believe that any app with access to your sensitive data shouldn't have internet permissions, and I want to keep it that way. In fact I'm actually leaning towards #50 to also remove SD card permissions as well.

2. I admit the NekoSMS UI is terrible, but I don't have the ability to improve it (because I suck at design/making custom UI components). This also seems like a rather large effort for fairly minimal gain. If someone else were willing to implement this I'd be open to it, but I don't have the time to do this myself, sorry :-(

**Comment by dudu485** [comment]
1我喜欢NekoSMS的界面   足够精简   作为一个工具来说  完美了   
2 忽略了你提到的联网权限  的确 任何可以访问到敏感数据的  都不应该有过多的权限   解决这个   或者只是增加一个单纯的导入导出规则的按钮就好   至于规则哪里获得  这个或者可以考虑在这里开设一个共享的空间  由大家自由下载

**Comment by apsun** [comment]
Sorry, I don't understand, there already is a button to import and export filter rules. As for where you can share them, that is outside the scope of this project; they're just simple JSON files, you can just host them on GitHub if you want.
