### ISSUE TITLE
希望支持通知分组和折叠

### ISSUE THREAD

**Issue by ClareChen** [apsun/NekoSMS#64]
Write your issue description here.

--- 垃圾短信多了很占用通知中心空间，希望可以将多条拦截通知折叠到一起。

**If you are submitting a bug report and do not include the following info, your issue will be ignored!**

- Device: 
- Android version: 
- Xposed version: 
- NekoSMS version: 

Please paste your Xposed logs (Xposed Installer -> Logs -> Menu -> Save to SD card) below:

```
Replace this line with your logs. Do not remove the backticks.
```

Thank you for helping us help you help us all.

**Comment by apsun** [comment]
This actually used to be a feature, but I intentionally removed it in https://github.com/apsun/NekoSMS/commit/8a56acbc3c1d5d6001acc3ee5ba529a1646dd9ad because it was causing problems with some versions of Android. Unfortunately I will not be fixing this, because the amount of effort required to deal with this compatibility bullshit is more than it's worth. I would advise you to just turn off notifications if they bother you. Sorry.
